src/FH/Bundle/AppBundle/Entity/Question.php
<?php

namespace FH\Bundle\AppBundle\Entity;

/**
 * @author Bart van Amelsvoort <bart@freshheads.com>
 */
class Question
{
    const TYPE_MOVIE_IMAGE = 'movie_image';

    /**
     * @var integer
     */
    private $id;

    /**
     * @var string
     */
    private $type;

    /**
     * @var string
     */
    private $image;

    /**
     * @var string
     */
    private $answerA;

    /**
     * @var string
     */
    private $answerB;

    /**
     * @var string
     */
    private $answerC;

    /**
     * @var string
     */
    private $answerD;

    /**
     * @var string
     */
    private $correctAnswer;

    /**
     * @return int
     */
    public function getId()
    {
        return $this->id;
    }

    /**
     * @return string
     */
    public function getType()
    {
        return $this->type;
    }

    /**
     * @return string
     */
    public function getImage()
    {
        return $this->image;
    }

    /**
     * @return string
     */
    public function getAnswerA()
    {
        return $this->answerA;
    }

    /**
     * @return string
     */
    public function getAnswerB()
    {
        return $this->answerB;
    }

    /**
     * @return string
     */
    public function getAnswerC()
    {
        return $this->answerC;
    }

    /**
     * @return string
     */
    public function getAnswerD()
    {
        return $this->answerD;
    }

    /**
     * @return string
     */
    public function getCorrectAnswer()
    {
        return $this->correctAnswer;
    }

    public function getTitle()
    {
        switch ($this->type) {
            case self::TYPE_MOVIE_IMAGE:
                return 'Welke film is dit?';
        }
    }

    public function getImagePath()
    {
        return sprintf('images/question/%s', $this->image);
    }
}

src/FH/Bundle/AppBundle/Controller/QuestionController.php
<?php

namespace FH\Bundle\AppBundle\Controller;

use Doctrine\ORM\EntityManager;
use FH\Bundle\AppBundle\Entity\Question;
use FH\Bundle\AppBundle\Entity\QuestionAnswer;
use FH\Bundle\AppBundle\Entity\User;
use FH\Bundle\AppBundle\User\LoginUser;
use Symfony\Component\HttpFoundation\RedirectResponse;
use Symfony\Component\HttpFoundation\Request;
use FH\Bundle\AppBundle\Repository\QuestionRepository;
use Sensio\Bundle\FrameworkExtraBundle\Configuration\Template;
use Symfony\Component\Routing\Generator\UrlGeneratorInterface;

/**
 * @author Bart van Amelsvoort <bart@freshheads.com>
 */
class QuestionController
{
    /**
     * @var QuestionRepository
     */
    private $questionRepository;

    /**
     * @var LoginUser
     */
    private $loginUser;

    /**
     * @var UrlGeneratorInterface
     */
    private $urlGenerator;

    /**
     * @var EntityManager
     */
    private $entityManager;

    /**
     * @param QuestionRepository $questionRepository
     * @param LoginUser $loginUser
     * @param UrlGeneratorInterface $urlGenerator
     * @param EntityManager $entityManager
     */
    public function __construct(
        QuestionRepository $questionRepository,
        LoginUser $loginUser,
        UrlGeneratorInterface $urlGenerator,
        EntityManager $entityManager
    ) {
        $this->questionRepository = $questionRepository;
        $this->loginUser = $loginUser;
        $this->urlGenerator = $urlGenerator;
        $this->entityManager = $entityManager;
    }

    /**
     * @Template
     *
     * @param Request $request
     * @param Question $question
     * @param string $answer
     * @return array
     */
    public function detailAction(Request $request, Question $question, $answer = null)
    {
        /** @var User $currentUser */
        $currentUser = $this->entityManager->merge($this->loginUser->getUser());

        if ($answer) {
            $correct = $answer == $question->getCorrectAnswer();
            $consumption = new QuestionAnswer($currentUser, $question, $correct);

            $this->entityManager->persist($consumption);
            $this->entityManager->flush();

            return new RedirectResponse(
                $this->urlGenerator->generate('home')
            );
        }

        return [
            'question' => $question
        ];
    }
}

src/FH/Bundle/AppBundle/Resources/views/Question/detail.html.twig
{% extends '::base.html.twig' %}

{% block content %}
    
        <h1>{{ question.title }}</h1>
        <img class='quiz_img' src="{{ asset(question.imagePath) }}" alt="{{ question.title }}" />
    <section id='quiz_options'>
        <a class= 'quiz_answer' href="{{ path('question_detail', { id: question.id, answer: 'a' }) }}">{{ question.answerA }}</a>
        <a class= 'quiz_answer' href="{{ path('question_detail', { id: question.id, answer: 'b' }) }}">{{ question.answerB }}</a>
        <a class= 'quiz_answer' href="{{ path('question_detail', { id: question.id, answer: 'c' }) }}">{{ question.answerC }}</a>
        <a class= 'quiz_answer' href="{{ path('question_detail', { id: question.id, answer: 'd' }) }}">{{ question.answerD }}</a>
    </section>
{% endblock %}

src/FH/Bundle/AppBundle/Resources/views/Question/index.html.twig
{% extends '::base.html.twig' %}

{% block content %}
    {{ question.title }}

    <form method="post">
        <label for="a">{{ question.answerA }}</label>
        <input type="radio" id="a" name="answer" value="a" />
        <br />

        <label for="b">{{ question.answerB }}</label>
        <input type="radio" id="b" name="answer" value="b" />
        <br />

        <label for="c">{{ question.answerC }}</label>
        <input type="radio" id="c" name="answer" value="c" />
        <br />

        <label for="d">{{ question.answerD }}</label>
        <input type="radio" id="d" name="answer" value="d" />

        <input type="submit" value="Verstuur" />
    </form>
{% endblock %}